# Generated by Django 5.1.5 on 2025-01-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='gmail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default='blank@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
