# Generated by Django 5.1.5 on 2025-01-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
