# Generated by Django 5.1.5 on 2025-01-24 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0002_writer_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
    ]
