# Generated by Django 5.1.5 on 2025-01-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_tag_quote_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='quotes.tag'),
        ),
    ]
