# Generated by Django 5.1.5 on 2025-01-24 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.tag'),
        ),
    ]
